
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const RoleType = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE'
} as const

export type RoleType = (typeof RoleType)[keyof typeof RoleType]


export const EmploymentLevel = {
  JUNIOR: 'JUNIOR',
  MID: 'MID',
  SENIOR: 'SENIOR',
  LEAD: 'LEAD'
} as const

export type EmploymentLevel = (typeof EmploymentLevel)[keyof typeof EmploymentLevel]


export const EmploymentStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LEAVE: 'LEAVE'
} as const

export type EmploymentStatus = (typeof EmploymentStatus)[keyof typeof EmploymentStatus]


export const ProjectStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED'
} as const

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus]


export const TaskStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELED: 'CANCELED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority]


export const PositionName = {
  ENGINEERING_MANAGER: 'ENGINEERING_MANAGER',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  SCRUM_MASTER: 'SCRUM_MASTER',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  FRONTEND_DEVELOPER: 'FRONTEND_DEVELOPER',
  BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
  FULLSTACK_DEVELOPER: 'FULLSTACK_DEVELOPER',
  DEVOPT_ENGINEERING: 'DEVOPT_ENGINEERING',
  QA_ENGINEER: 'QA_ENGINEER',
  QA_AUTOMATE_ENGINEER: 'QA_AUTOMATE_ENGINEER',
  SOFTWARE_TESTER: 'SOFTWARE_TESTER',
  UX_DESIGNER: 'UX_DESIGNER',
  UI_DESIGNER: 'UI_DESIGNER',
  UX_UI_DESIGNER: 'UX_UI_DESIGNER',
  SYSTEM_ADMINISTRATOR: 'SYSTEM_ADMINISTRATOR',
  CLOUD_ENGINEERING: 'CLOUD_ENGINEERING',
  DATABASE_ADMINISTRATOR: 'DATABASE_ADMINISTRATOR'
} as const

export type PositionName = (typeof PositionName)[keyof typeof PositionName]
